version: "2"
services:
  plone:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.api.versions
    environment:
      ADDONS: "eea.api.versions[test]"
      DEVELOP: "src/eea.api.versions"
